### ISSUE TITLE
subsubsections have a different style in HTML and PDF

### ISSUE THREAD

**Issue by deronnax** [mszep/pandoc_resume#64]
### Expected Behavior
subsubsection should not have a green bar in PDF, as the they don't in HTML.
PDF:
<img width="1203" alt="PDF subsubsection" src="https://user-images.githubusercontent.com/439279/69381089-41742a00-0cb4-11ea-9ba8-43a445bdc5be.png">
HTML:
<img width="801" alt="HTML subsubsection" src="https://user-images.githubusercontent.com/439279/69381094-446f1a80-0cb4-11ea-942d-42ffbc44afef.png">

### Actual Behavior
subsubsection have a green bar in PDF

### Steps to reproduce the behavior
just make a markdown document with subsubsection  (`###` in markdown)
### Versions

Pandoc and context versions

version independant, it's a style problem

 If you fix it before monday, I'll give you a 15€ tip through paypal. I'm dead serious.

**Comment by mszep** [comment]
The original style this project was inspired from had green bars for all section levels, but of varying length. I don't know if this was changed in the pdf intentionally to have them be of equal length, but having a green bar in the pdf is in fact the expected behaviour.

I'm afraid I don't have time to work on this right now, so you'll have to tweak the context style file yourself to change the style for subsubsections.
